apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-app
  labels:
    app: netology-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology-app
  template:
    metadata:
      labels:
        app: netology-app
    spec:
      containers:
      - name: netology-app
        image: sokolkovnetology/netology-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netology-app
spec:
  type: NodePort
  selector:
    app: netology-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081
