#cloud-config
users:
  - name: sokolkov
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFxlZ1Mm8NQACMSr9usInKXn9mouCt0U2hR2cSdC/i6O sokolkov.pa@NB-ISC-737640
